### ISSUE TITLE
Week 1 Team Review Ticket

### ISSUE THREAD

**Issue by chenxin-chex** [dsblack0/stickers_for_charity#21]
Wiki and github pages has project requirements:
- [Github page](https://dsblack0.github.io/stickers_for_charity/)
- [Evidence of Communication](https://drive.google.com/file/d/1hqfoVJDW07zd9IX9RroLRLeotddEHww8/view?usp=sharing) <-- From SFC Meeting Notes

Scrum Board has all jobs described and assigned to team members, including in progress task: 
- [Scrum Board](https://github.com/dsblack0/stickers_for_charity/projects/1)
- [In Progress Tasks](https://github.com/dsblack0/stickers_for_charity/projects/1#column-18097221)

**Comment by wrachel** [comment]
Grading: 
1/1 
Contains evidence of requirements and has very clear requirements: [link](https://dsblack0.github.io/stickers_for_charity/projectPlans) as well as evidence that there was a meeting going over their requirements. They also had many additional team ideas (aside from their requirements), and wireframe ideas for their project.

Their scrum board is also started, and has in-progress tasks for everyone. [link here](https://github.com/dsblack0/stickers_for_charity/projects/1). Overall, they look like they are going on the right track and has everything set up.

**Comment by jm1021** [comment]
Stickers for Charity.  Next step see more flow of web site.   Technical plan is needed for assignment.  

.9/1
