### ISSUE TITLE
Crossover Presentation

### ISSUE THREAD

**Issue by KaavyaU** [dsblack0/stickers_for_charity#29]
[Presentation](https://docs.google.com/presentation/d/15eE8S6gadsTjSOaAEU70A4pq0eFdSe4asBgLAlON8TM/edit?usp=sharing)
[Crossover Feedback](https://dsblack0.github.io/stickers_for_charity/projectFeedback)

**Comment by jm1021** [comment]
Stickers for Charity Club.   Arushi is president.

A webpage to interact with customers of Club.   Very clear on initial requires.  

AWS EC2, they determined club can manage costs.   Discussed licensing and removing themself from liability.

They discussed admin and accounts.   Had workflow and broken lines showing admin.   Lots of thought went into who does what.  Solved problem of purchase with PayPal.

Individual profile and bio discussed for people on site.  Events may be managed by profile?  

Lots of great though and sensibility throughout discussions.

They consider design and colors.  They had several wires with information on each that seem to have a lot of deep thought.   Pages even have reviews, content, light and dark and much more.
