### ISSUE TITLE
Week 3 Maggie Review Ticket

### ISSUE THREAD

**Issue by maggie3000** [dsblack0/stickers_for_charity#36]
**Week 3 Maggie Individual Review Ticket**
**TOTAL SCORE: 4.9/5**
**Graded by: Sammy**

Links:
[Github Pages](https://maggie3000.github.io/CSAindividualrepoTRI3/)
[Repl.it](https://replit.com/@MaggieKillada/CSAindividualrepoTRI3?v=1)
[Individual Repo](https://github.com/maggie3000/CSAindividualrepoTRI3)

**Comment by SamiDeshatty** [comment]
###CROSSOVER GRADE: 4.9/5

##Sorts and Analysis -- Coding, Comments, and Documentation

- Build custom Bubble Sort, Selection Sort, Insertion Sort and Merge Sort. 25%
0.9/1 Insertion Sort not working but attempted and implemented.

- Build a GitHub page that describes Sort implementations and the Big O complexity of these Sorts. 25%
#1/1 Github page (Data structure branch) explains all the Sort implementations; Big O complexity of every sort is presented.

##Analysis 25%

- Establish analytics including: time, comparisons and swaps.

- Average the results for each each Sort, run each at least 12 times and 5000 elements.  You should throw out High and Low when doing analysis.

- Make your final/judgement on best sort considering Data Structure loading, Comparisons, Swaps, Big O complexity, and Time.
#1/1 Time is present in nanoseconds; Sort runs more than 12 times and has more than 5000 elements; Everything is present perfectly.

##Individual GitHub pages, Replit, IntelliJ 25%

- Organize files, directories and menus for all weeks.

- Make your GitHub pages fold into a personal portfolio

- Make sure all Code and Analytics runs on Replit and IntelliJ

- Ensure Individual GitHub Repository shows iteration on work (minimum of 10 commits on Java and 10 commits on Pages)

#2/2 All weeks are presented separately in Github and Replit; Personal Portfolio present in Github; All code in committed on github into replit; 400+ commits on Java and Pages combined
