### ISSUE TITLE
Study Week 1 - Chenxin

### ISSUE THREAD

**Issue by chenxin-chex** [dsblack0/stickers_for_charity#42]
## Score: 5/5 (Graded by Jonathan)
 - [x] [-/1.25] Study plan for week on [github pages](https://chenxin-chex.github.io/Chenxin-Individual-Tri-3/Test_Prep)
 - [x] [-/1.25] MCQ Results and Corrections: 31/39 and [Link](https://docs.google.com/document/d/1ujr91rdWfHPPWm8cg4qDUWVrFLO7De7-n-vt1pBCNUQ/edit?usp=sharing) 
 - [x] [-/1.25] FRQ: Screenshots in [github pages](https://chenxin-chex.github.io/Chenxin-Individual-Tri-3/FRQ_Code) and running in [Replit](https://replit.com/@chenxinNi/2015FRQ#Main.java)
 - [x] [-/1.25] Self Study Guide: [Link](https://docs.google.com/document/d/12narkOSmUhjDSDolaq9iwvMJ0JjleAJVYIBYRwUyeUQ/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/55467785/165137570-5c69e9d3-eb46-480a-beb3-a808d61549ee.png)
![image](https://user-images.githubusercontent.com/55467785/165137595-d09493f2-b4bb-4d18-85ac-0e2b39cff643.png)
![image](https://user-images.githubusercontent.com/55467785/165137620-83be278d-3ca2-4dcd-aa7e-8b366513cb82.png)
![image](https://user-images.githubusercontent.com/55467785/165137853-2c4a37d3-1b4a-4fb9-9173-4e8840f26be5.png)
![image](https://user-images.githubusercontent.com/55467785/165137765-7b15da7f-e1f1-4ac1-8698-e0f7ed5f6a4a.png)

**Comment by armarmgc** [comment]
# Score 5/5

- 1.25/1.25 Study plan on [github pages][] with general goals and plan for each day for week 1.
- 1.25/1.25 MCQ corrections on a [google doc](https://docs.google.com/document/d/1ujr91rdWfHPPWm8cg4qDUWVrFLO7De7-n-vt1pBCNUQ/edit), showing total result, and incorrect answer, correct answer, and explanation on why she got it wrong for each question incorrect.
- 1.25/1.25 FRQ with pictures on [github pages][] and running on [replit][]
- 1.25/1.25 Study guide on a [google doc] https://docs.google.com/document/d/12narkOSmUhjDSDolaq9iwvMJ0JjleAJVYIBYRwUyeUQ/edit) with table of contents to notes for tech talks and videos, and test corrections.

[github pages]: https://chenxin-chex.github.io/Chenxin-Individual-Tri-3/Test_Prep
[replit]: https://docs.google.com/document/d/1ujr91rdWfHPPWm8cg4qDUWVrFLO7De7-n-vt1pBCNUQ/edit
