### ISSUE TITLE
Study Week 2 Review Ticket - Sam

### ISSUE THREAD

**Issue by dsblack0** [dsblack0/stickers_for_charity#46]
### [Rachel's Ticket](https://github.com/wrachel/Data-Structures-Indiv/issues/7) that I graded

- [x] [Github Pages](https://dsblack0.github.io/sam-tri3/testPrep) with AP review material

- [x] [2020 MCQ](https://dsblack0.github.io/sam-tri3/2020mc) Score + Corrections
![image](https://user-images.githubusercontent.com/70492417/166409708-1ec90cef-af73-44d9-9bd1-a535d1f15cf1.png)

- [x] FRQ [paper code](https://dsblack0.github.io/sam-tri3/2020frq) & [repl](https://dsblack0.github.io/sam-tri3/code)
- All the mistakes I made & the correct approach for the code is marked in my code through comments
- Note: I had to fix a bigger mistake in my code for question 2 (I originally didn't make a variable static when it needed to be) because it was preventing the code for other question from running properly on Repl.

- [x] Overall [review progress](https://dsblack0.github.io/sam-tri3/testPrep#study-week-2)
- [study guide](https://github.com/dsblack0/sam-tri3/blob/gh-pages/csa_studyguide.pdf) + [additional mc practice](https://dsblack0.github.io/sam-tri3/reviewQuizzes#52-question-practice-mc)

**Comment by wrachel** [comment]
1. MCQ Results
* 1/1, Had a score greater than 50%, and did thorough reflections for each incorrect answer. Did corrections for 8 questions. Reflections are here: [https://dsblack0.github.io/sam-tri3/2020mc](https://dsblack0.github.io/sam-tri3/2020mc)

2. FRQ Results
* 1/1, FRQ was done, the image of the FRQs: [https://dsblack0.github.io/sam-tri3/2020frq](https://dsblack0.github.io/sam-tri3/2020frq) had over 50% done from in-class. Replit [here](https://dsblack0.github.io/sam-tri3/code) is running all 3 FRQs from the ones she did in class. 
* Overall, really good work with FRQs: did 3 problems within the short time allotted and implemented them all in Repl

3. Ticket, GH Pages, Corrections, REPL, running FRQs
* 1/1, extreme effort was made
* Did all MC & FRQ assignments thoroughly and even did **EXTRA** work to study 
* She did a lot of additional MC practice to study: [https://dsblack0.github.io/sam-tri3/reviewQuizzes#52-question-practice-mc](https://dsblack0.github.io/sam-tri3/reviewQuizzes#52-question-practice-mc) and also worked on an individual study guide [here](https://github.com/dsblack0/sam-tri3/blob/gh-pages/csa_studyguide.pdf)
* She also has a thorough plan she used to review and prepare for the AP exam: [here](https://dsblack0.github.io/sam-tri3/testPrep#study-week-2)

4. Participation
* 1/1, was present for every day in class (0.2*5 = 1)
