### ISSUE TITLE
Study Week 2 - Maggie

### ISSUE THREAD

**Issue by maggie3000** [dsblack0/stickers_for_charity#47]
### Maggie Killada - Study Week 2
**SCORE: 2.5/4.5**
**Reviewed by: Prisha**
[Crossover Grading For Prisha](https://github.com/PrishaMaiti/DataStructures/issues/8)

LINKS:\
[repl.it](https://replit.com/@MaggieKillada/CSAindividualrepoTRI3?v=1)\
[GH Test Prep Page](https://maggie3000.github.io/CSAindividualrepoTRI3/testprep)\
[GH Study Guide Page](https://maggie3000.github.io/CSAindividualrepoTRI3/studyguide)\
[Review ticket](https://github.com/dsblack0/stickers_for_charity/issues/47)\
[MCQ Results & Corrections(15/20)](https://docs.google.com/document/d/1L2rZ6Yk7f2eXbvjItyEQpIPA8XX2jW4meKFb7r59ZWM/edit?usp=sharing)\
[week 2 FRQ 1 on Paper (didn't finish FRQ 2)](https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/images/IMG_2978.HEIC)\
[week 2 FRQ 1 on Repl.it](https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/frq/Hailstone.java)\
[week 2 FRQ 2 on Repl.it](https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/frq/GameSpinner.java)\
OTHER ADDITIONAL WORK THIS WEEK:\
[AP Classroom Quizzes](https://docs.google.com/document/d/1olCd6bjQjRe6h0K7HsPLtSCNvIDgRzOFAkKTWw1dlHs/edit?usp=sharing)\
[AP CSA 2020 Released Sample FRQ #1](https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/frq/Gizmo.java)
[(more code)](https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/frq/OnlinePurchaseManager.java)\
[AP CSA 2020 Released Sample FRQ #2](https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/frq/CheckDigit.java)\
Note: I've been watching AP live videos on the youtube channel and doing practice questions from the videos as well.

**Comment by maggie3000** [comment]
3 points, use bullets as indicated above, 1 point per sub-bullet
1 point, Participation: .20 for classroom presence and participation each day   
.5 point, Quality of work:  grader should be looking at effort toward learning and understanding vs perfunctory bullet chasing (0, .25, .5).

**Comment by PrishaMaiti** [comment]
3 points, use bullets as indicated above, 1 point per sub-bullet (MCQ Results > 50% Not more than 50%. 0) (FRQ Results > 50%. Even though with menu, there are some compilation errors, individual files seem to be running correctly. .+1) (With menu, there are a couple of compiler errors, so work on REPL is only partially done. Everything else seems to be in place with full effort and completion. .5/1)
1 point, Participation: .20 for classroom presence and participation each day (+.20 per day for attending school and coding)
.5 point, Quality of work: grader should be looking at effort toward learning and understanding vs perfunctory bullet chasing (0, .25, .5). (She is clearly trying to understand from MCQ mistakes regardless of the score being less than 50% and recover from original FRQ attempts to make running FRQs. +.5)
