### ISSUE TITLE
Study Week 2 - Chenxin

### ISSUE THREAD

**Issue by chenxin-chex** [dsblack0/stickers_for_charity#48]
### Score: 4.5/5, Graded By: Akhil

Graded Kaavya: [Kaavya's ticket](https://github.com/dsblack0/stickers_for_charity/issues/49)

 - [-/1] MCQ results: 32/40
![image](https://user-images.githubusercontent.com/55467785/166505349-7688e0a2-68f6-4f63-97ab-b4e45bf00c5f.png)
 - [-/1] MCQ [corrections](https://docs.google.com/document/d/1Ot0aV9J60tbbi0bbH1L66sfnywC9O4aj9Mflox2DdoQ/edit?usp=sharing)
 - [-/1] FRQ code screenshots on [github pages](https://chenxin-chex.github.io/Chenxin-Individual-Tri-3/FRQ_Code) and running on [Replit](https://replit.com/@chenxinNi/2020FRQ#Main.java)
 - [-/1] Daily participation (have attended class everday last week)
 - [-/.5] Quality of work

**Comment by algolg** [comment]
Score: 4.5/5
Graded By Akhil

- [x] (1/1) MCQ results are given with a score well over 50%
- [x] (1/1) Written FRQ answers are on GitHub pages and code seems to be correct. Everything is very neat. One thing to watch out for is that we might be required to use pen on the AP exam.
- [x] (1/1) MCQ corrections are detailed and give good explanations for the correct answers. FRQs are deployed on Replit but it's hard to tell which part of the printed output belongs to each FRQ, so I would recommend adding details in the main method of the Main class.
- [x] (1/1) Participated daily last week and had a main role in ASI project
- [x] (0.5/5) High quality of work as shown by the detail put into MCQ corrections and FRQs
