### ISSUE TITLE
Study Week 2 - Kaavya

### ISSUE THREAD

**Issue by KaavyaU** [dsblack0/stickers_for_charity#49]
### Graded Akhil's [Review Ticket](https://github.com/algolg/akhil-t3/issues/14)

2020 MCQ
![Capture](https://user-images.githubusercontent.com/72475036/166521358-b2467b45-677f-4e00-9878-22bb4131b42e.PNG)
- [2020 MCQ Corrections](https://docs.google.com/document/d/1lKgTZCheP5DQr6eGg5GOhTLHsJOgMOnl58e57MxlMrQ/edit?usp=sharing)

2020 FRQ
- [Paper Code](https://kaavyau.github.io/Kaavya_Individual_Tri3/Test_Prep#week-2-frq-paper-submission)
- [Repl Runtime ](https://replit.com/@KaavyaUppala/KaavyaIndividualTri3#Main.java)
-  2 out of 4 FRQs running correctly. Other two have minor errors that are corrected w/ comments

GitHub Pages:
- [Overall Github Pages](https://github.com/KaavyaU/Kaavya_Individual_Tri3/blob/main/Test_Prep.md)
- [Start of Week 2](https://kaavyau.github.io/Kaavya_Individual_Tri3/Test_Prep#week-2-units-6-10)

**Comment by chenxin-chex** [comment]
### Score: 4.3/5

 - [1/1] MC results is greater than 50%
 - [1/1] 2 FRQ questions are completed, running on replit, and screenshots on github pages
 - [1/1] MC Corrections done
 - [.8/1] -0.2 because missed attendance last week
 - [.5/.5] Quality work
