### ISSUE TITLE
Team Clouds Presentation Review Ticket 

### ISSUE THREAD

**Issue by chenxin-chex** [dsblack0/stickers_for_charity#50]
Team members: Chenxin Ni, Prisha Maiti, Maggie Killada, Kaavya Uppala, Samhitha Duggirala

Grading criteria:
 - [x] Visualize ideas - [Wireframe Presentation](https://docs.google.com/presentation/d/1bJK0mjS-OzZ1H4lfNiHI4ZFaRIz9ZaQ5aZCExAhJdbE/edit?usp=sharing) and code running
 - [x] Understand features - [Scrum Board](https://github.com/dsblack0/stickers_for_charity/projects/1) is populated with issues and tasks. [Github pages](https://dsblack0.github.io/stickers_for_charity/) has project plans and technicals described
 - [x] Overall quality

**Comment by QwikSP** [comment]
CB: Primitive Apes
Grade: 3/3

### Visualize ideas presentations of running code, GH pages,  and concepts/visuals of future project

1/1
### Understand features Issues/Tickets, Project Board, GH Pages, time box, future features, and technical in the project
1/1
### Overall quality, clarity and presentation of the project
1/1

**Comment by ArnavPalkhiwala** [comment]
**Score: 3/3**
- [ ]  Ideas Visualized: We really like the UML diagram which was a bit confusing at first, but later on, was very easy to understand and makes a lot of sense
- [ ]  Understandable Features: (tickets, scrumboard, roles, etc.): I liked the features and the goal and group made their goals extremely clear, which was very helpful for us seeing the presentation
- [ ]  Overall Quality: Very nice presentation; I liked all of the tangibles that were showed; it is clear that a lot of work is put in
Comments:
I like how you made a website for another club; it is similar to our idea and easy to understand the use case

**Comment by elw55555** [comment]
CB: the-shop
Grade: 3/3

Visualize ideas presentations of running code, GH pages, and concepts/visuals of future project: 1/1

Understand features Issues/Tickets, Project Board, GH Pages, time box, future features, and technical in the project: 1/1

Overall quality, clarity and presentation of the project: 1/1

Comments: You guys had a lot to say and a very visually-appealing project. It looks nice.
