### ISSUE TITLE
Chenxin Final Dev 1 Review Ticket

### ISSUE THREAD

**Issue by chenxin-chex** [dsblack0/stickers_for_charity#57]
Individual grade out of 2 points

Meet goals for Week 1 (-/1 points):
 - [x] Deploy website on AWS
 - [x] Get started with Sticker order page framework: [Issue](https://github.com/dsblack0/stickers_for_charity/issues/19)

Individual work tangibles (-/1 points): 
 - Commit work on Sticker Order page [evidence](https://github.com/dsblack0/stickers_for_charity/commits?author=chenxin-chex)
 - Website is deployed at [stickersforcharity.tk](stickersforcharity.tk)

Port routing not working because router isn't working (will finish later)
AWS and nginx server is running 
![image](https://user-images.githubusercontent.com/55467785/169203585-6c557256-44b2-4177-876f-77580819fd77.png)

Domain is running
![image](https://user-images.githubusercontent.com/55467785/169097655-a46549a8-13dd-4352-9d2d-13f2e2339bf8.png)

**Comment by KaavyaU** [comment]
### Scrum Master Grading (1.8/1.8)
- Meeting 5 hours with commit evidence --> 0.9/0.9 pt
     - Multiple commits from multiple different days
     - Most work done on AWS, so understandable that not as many PBL commits this week
     - Observed to be working diligently during entirety of class time
- Meeting team and sponsor objectives --> 0.9/0.9 pt
     - Met almost all the requirements outlined in [Week 1 Plan](https://github.com/dsblack0/stickers_for_charity/issues/61) w/ tangibles for proof
     - Plan for finishing port forwarding already made and will be completed before Teacher Review
