### ISSUE TITLE
Sam Final Dev 1 Review Ticket

### ISSUE THREAD

**Issue by dsblack0** [dsblack0/stickers_for_charity#58]
## Commits
- [x] [main branch](https://github.com/dsblack0/stickers_for_charity/commits?author=dsblack0)
     - about team page + login page
- [x] [aboutTeamDatabase branch](https://github.com/dsblack0/stickers_for_charity/commits/aboutTeamDatabase?author=dsblack0)

### Week 1 Progress
- [x] Finish frontend HTML for ["About Team"](https://github.com/dsblack0/stickers_for_charity/issues/12) page(s)
      - [html](https://github.com/dsblack0/stickers_for_charity/blob/master/src/main/resources/templates/aboutTeam.html)
- [x] Finish frontend HTML for ["Login Page"](https://github.com/dsblack0/stickers_for_charity/issues/20)
     - [html](https://github.com/dsblack0/stickers_for_charity/blob/master/src/main/resources/templates/login.html)
- [x] Add about team information provided by club - temporary data until database completed
     - [java](https://github.com/dsblack0/stickers_for_charity/blob/master/src/main/java/com/example/sping_portfolio/controllers/aboutTeam.java)

### Additional Progress
- [x] started database for "About Team Page"
     - [java](https://github.com/dsblack0/stickers_for_charity/tree/aboutTeamDatabase/src/main/java/com/example/sping_portfolio/controllers/aboutTeam)
     - [html](https://github.com/dsblack0/stickers_for_charity/blob/aboutTeamDatabase/src/main/resources/templates/aboutTeam/aboutTeamEdit.html)

**Comment by KaavyaU** [comment]
### Scrum Master Grading (1.8/1.8)
- Meeting 5 hours with commit evidence --> 0.9/0.9 pt
     - Multiple meaningful commits from multiple different days
     - Observed to be working diligently during entirety of class time
- Meeting team and sponsor objectives --> 0.9/0.9 pt
     - Met all the requirements outlined in [Week 1 Plan](https://github.com/dsblack0/stickers_for_charity/issues/61) w/ tangibles for proof
     - Went above and beyond by tackling next weeks task of databases as well
