### ISSUE TITLE
Prisha Final Dev 1 Review Ticket

### ISSUE THREAD

**Issue by PrishaMaiti** [dsblack0/stickers_for_charity#62]
## Commits (2 most important ones for the week):
- [x] [Commit on branch prisha/database](https://github.com/dsblack0/stickers_for_charity/commit/aebd17d71d3cfd1cc72ff481f746072ef75ce684)
- [x] [On branch prisha/database](https://github.com/dsblack0/stickers_for_charity/commit/340073539a7bce951814256669b171d93c7a8dfa)

## Week 1 Progress
- [x] Added Club_Member role using Sqlite (check through terminal)
- [x] Added the person [POJO](https://github.com/dsblack0/stickers_for_charity/blob/prisha/database/src/main/resources/templates/database/person.html) and person [create](https://github.com/dsblack0/stickers_for_charity/blob/prisha/database/src/main/resources/templates/database/personcreate.html) and [update](https://github.com/dsblack0/stickers_for_charity/blob/prisha/database/src/main/resources/templates/database/personupdate.html) files for signup database (the same code for these files will also be used for the following week's reviews page database)

**Comment by KaavyaU** [comment]
### Scrum Master Grading (1.8/1.8)
- Meeting 5 hours with commit evidence --> 0.9/0.9 pt
     - Multiple commits from multiple different days
     - Worked everyday consistently
     - Worked w/ Mr. M to get the code working (classtime was used efficiently)
- Meeting team and sponsor objectives --> 0.9/0.9 pt
     - Met all the requirements outlined in [Week 1 Plan](https://github.com/dsblack0/stickers_for_charity/issues/61) w/ tangibles for proof
     - Worked w/ Database and created roles as Mr. M required (allows Sam to do her work w/ the database security next week)
